// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &User{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// UserParameters are the configurable fields of a User.
//
// These are the fields of the create request body (UserPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// UserObservation instead.
type UserParameters struct {
	// CustomFields Structure for uploading custom field values in POSTs and PUTs.
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	CustomFields string `json:"CustomFields,omitempty"`

	// RealName
	// +optional
	RealName string `json:"RealName,omitempty"`

	// NickName
	// +optional
	NickName string `json:"NickName,omitempty"`

	// EmailAddress
	// +optional
	EmailAddress string `json:"EmailAddress,omitempty"`

	// Gecos \&quot;Unix login\&quot; in the UI
	// +optional
	Gecos string `json:"Gecos,omitempty"`

	// Lang
	// +optional
	Lang string `json:"Lang,omitempty"`

	// Timezone
	// +optional
	Timezone string `json:"Timezone,omitempty"`

	// FreeformContactInfo \&quot;Extra info\&quot; in the UI
	// +optional
	FreeformContactInfo string `json:"FreeformContactInfo,omitempty"`

	// Comments Comments about the user.
	// +optional
	Comments string `json:"Comments,omitempty"`

	// WorkPhone
	// +optional
	WorkPhone string `json:"WorkPhone,omitempty"`

	// MobilePhone
	// +optional
	MobilePhone string `json:"MobilePhone,omitempty"`

	// HomePhone
	// +optional
	HomePhone string `json:"HomePhone,omitempty"`

	// PagerPhone
	// +optional
	PagerPhone string `json:"PagerPhone,omitempty"`

	// Organization
	// +optional
	Organization string `json:"Organization,omitempty"`

	// Address1
	// +optional
	Address1 string `json:"Address1,omitempty"`

	// Address2
	// +optional
	Address2 string `json:"Address2,omitempty"`

	// City
	// +optional
	City string `json:"City,omitempty"`

	// Zip
	// +optional
	Zip string `json:"Zip,omitempty"`

	// State
	// +optional
	State string `json:"State,omitempty"`

	// Country
	// +optional
	Country string `json:"Country,omitempty"`

	// Password Use a strong password!
	// +optional
	Password string `json:"Password,omitempty"`

	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`

	// Privileged Can this user be granted rights in RT?
	// +optional
	Privileged int64 `json:"Privileged,omitempty"`
}

// UserObservation are the observable fields of a User.
//
// These are the fields of the read response (UserIdNameGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type UserObservation struct {
	// CustomFields Customfields with their values, as returned by the server.
	CustomFields string `json:"CustomFields,omitempty"`

	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// RealName
	RealName string `json:"RealName,omitempty"`

	// NickName
	NickName string `json:"NickName,omitempty"`

	// EmailAddress
	EmailAddress string `json:"EmailAddress,omitempty"`

	// Gecos \&quot;Unix login\&quot; in the UI
	Gecos string `json:"Gecos,omitempty"`

	// Lang
	Lang string `json:"Lang,omitempty"`

	// Timezone
	Timezone string `json:"Timezone,omitempty"`

	// FreeformContactInfo \&quot;Extra info\&quot; in the UI
	FreeformContactInfo string `json:"FreeformContactInfo,omitempty"`

	// Comments Comments about the user.
	Comments string `json:"Comments,omitempty"`

	// WorkPhone
	WorkPhone string `json:"WorkPhone,omitempty"`

	// MobilePhone
	MobilePhone string `json:"MobilePhone,omitempty"`

	// HomePhone
	HomePhone string `json:"HomePhone,omitempty"`

	// PagerPhone
	PagerPhone string `json:"PagerPhone,omitempty"`

	// Organization
	Organization string `json:"Organization,omitempty"`

	// Address1
	Address1 string `json:"Address1,omitempty"`

	// Address2
	Address2 string `json:"Address2,omitempty"`

	// City
	City string `json:"City,omitempty"`

	// Zip
	Zip string `json:"Zip,omitempty"`

	// State
	State string `json:"State,omitempty"`

	// Country
	Country string `json:"Country,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`

	// Privileged Can this user be granted rights in RT?
	Privileged int64 `json:"Privileged,omitempty"`

	// Memberships
	Memberships string `json:"Memberships,omitempty"`

	// Hyperlinks
	Hyperlinks string `json:"_hyperlinks,omitempty"`
}

// A UserSpec defines the desired state of a User.
type UserSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              UserParameters `json:"forProvider"`
}

// A UserStatus represents the observed state of a User.
type UserStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A User is a managed RT user.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of User
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// User type metadata.
var (
	UserKind             = reflect.TypeOf(User{}).Name()
	UserGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserKind}.String()
	UserKindAPIVersion   = UserKind + "." + SchemeGroupVersion.String()
	UserGroupVersionKind = SchemeGroupVersion.WithKind(UserKind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
