// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Catalog{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// CatalogParameters are the configurable fields of a Catalog.
//
// These are the fields of the create request body (CatalogPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// CatalogObservation instead.
type CatalogParameters struct {
	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Description
	// +optional
	Description string `json:"Description,omitempty"`

	// Lifecycle Name of the lifecycle governing this catalog&#39;s assets.
	// +optional
	Lifecycle string `json:"Lifecycle,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// CatalogObservation are the observable fields of a Catalog.
//
// These are the fields of the read response (CatalogIdNameGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type CatalogObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// CustomFields Customfields with their values, as returned by the server.
	CustomFields string `json:"CustomFields,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// Lifecycle Name of the lifecycle governing this catalog&#39;s assets.
	Lifecycle string `json:"Lifecycle,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`
}

// A CatalogSpec defines the desired state of a Catalog.
type CatalogSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              CatalogParameters `json:"forProvider"`
}

// A CatalogStatus represents the observed state of a Catalog.
type CatalogStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 CatalogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Catalog is a managed RT catalog.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Catalog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CatalogSpec   `json:"spec"`
	Status CatalogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogList contains a list of Catalog
type CatalogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Catalog `json:"items"`
}

// Catalog type metadata.
var (
	CatalogKind             = reflect.TypeOf(Catalog{}).Name()
	CatalogGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogKind}.String()
	CatalogKindAPIVersion   = CatalogKind + "." + SchemeGroupVersion.String()
	CatalogGroupVersionKind = SchemeGroupVersion.WithKind(CatalogKind)
)

func init() {
	SchemeBuilder.Register(&Catalog{}, &CatalogList{})
}
