// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package user

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/ratelimiter"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

	"github.com/n-at-han-k/crossplane-provider-rt/apis/user/v1alpha1"
	apisv1alpha1 "github.com/n-at-han-k/crossplane-provider-rt/apis/v1alpha1"
	"github.com/n-at-han-k/crossplane-provider-rt/internal/clients/rt"
)

const (
	errTrackPCUsage = "cannot track ProviderConfig usage"
	errGetPC        = "cannot get ProviderConfig"
	errGetCPC       = "cannot get ClusterProviderConfig"
	errGetCreds     = "cannot get credentials"
	errNewClient    = "cannot create new Service"

	errGet    = "cannot get RT user"
	errCreate = "cannot create RT user"
	errUpdate = "cannot update RT user"
	errDelete = "cannot delete RT user"
	errParams = "cannot build the RT user request body"
	errParse  = "cannot parse the RT user response"

	// errNoID guards the one failure mode that silently leaks a resource: the
	// create succeeds but nothing in the answer carries an identifier. Setting
	// an empty external name would make every later Observe report
	// ResourceExists: false and create another one, forever.
	errNoID = "RT returned no user identifier from create; refusing to record an empty external name (one may have been created and needs manual cleanup)"
)

// newService builds the API client from the extracted credentials.
var newService = func(creds []byte) (*rt.Client, error) {
	return rt.NewClientFromCredentials(creds)
}

// SetupGated adds a controller that reconciles User managed resources with safe-start support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			panic(errors.Wrap(err, "cannot setup User controller"))
		}
	}, v1alpha1.UserGroupVersionKind)
	return nil
}

// Setup adds a controller that reconciles User managed resources.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.UserGroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*v1alpha1.User](&connector{
			kube:         mgr.GetClient(),
			usage:        resource.NewProviderConfigUsageTracker(mgr.GetClient(), &apisv1alpha1.ProviderConfigUsage{}),
			newServiceFn: newService,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))), //nolint:staticcheck // Crossplane has not moved to the new events API yet.
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}

	if o.Features.Enabled(feature.EnableAlphaChangeLogs) {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}

	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
	}

	if o.MetricOptions != nil && o.MetricOptions.MRStateMetrics != nil {
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.UserList{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind v1alpha1.UserList")
		}
	}

	r := managed.NewReconciler(mgr, resource.ManagedKind(v1alpha1.UserGroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(resource.DesiredStateChanged()).
		For(&v1alpha1.User{}).
		Complete(ratelimiter.NewReconciler(name, r, o.GlobalRateLimiter))
}

type connector struct {
	kube         client.Client
	usage        *resource.ProviderConfigUsageTracker
	newServiceFn func(creds []byte) (*rt.Client, error)
}

// Connect tracks the ProviderConfig usage, reads the (Cluster)ProviderConfig
// the resource names, extracts its credentials and forms a client from them.
func (c *connector) Connect(ctx context.Context, cr *v1alpha1.User) (managed.TypedExternalClient[*v1alpha1.User], error) {
	if err := c.usage.Track(ctx, cr); err != nil {
		return nil, errors.Wrap(err, errTrackPCUsage)
	}

	var cd apisv1alpha1.ProviderCredentials

	ref := cr.GetProviderConfigReference()

	switch ref.Kind {
	case "ProviderConfig":
		pc := &apisv1alpha1.ProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: cr.GetNamespace()}, pc); err != nil {
			return nil, errors.Wrap(err, errGetPC)
		}
		cd = pc.Spec.Credentials
	case "ClusterProviderConfig":
		cpc := &apisv1alpha1.ClusterProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name}, cpc); err != nil {
			return nil, errors.Wrap(err, errGetCPC)
		}
		cd = cpc.Spec.Credentials
	default:
		return nil, errors.Errorf("unsupported provider config kind: %s", ref.Kind)
	}

	data, err := resource.CommonCredentialExtractor(ctx, cd.Source, c.kube, cd.CommonCredentialSelectors)
	if err != nil {
		return nil, errors.Wrap(err, errGetCreds)
	}

	svc, err := c.newServiceFn(data)
	if err != nil {
		return nil, errors.Wrap(err, errNewClient)
	}

	return &external{service: svc}, nil
}

type external struct {
	service *rt.Client
}

// desired projects spec.forProvider onto the create request body. The JSON
// fields are strings in the CRD and real values on the wire, so they are
// unmarshalled here rather than passed through.
func desired(cr *v1alpha1.User) (*rt.UserPostRequest, error) {
	body := &rt.UserPostRequest{}

	if cr.Spec.ForProvider.CustomFields != "" {
		if err := json.Unmarshal([]byte(cr.Spec.ForProvider.CustomFields), &body.CustomFields); err != nil {
			return nil, errors.Wrap(err, "CustomFields")
		}
	}
	body.RealName = cr.Spec.ForProvider.RealName
	body.NickName = cr.Spec.ForProvider.NickName
	body.EmailAddress = cr.Spec.ForProvider.EmailAddress
	body.Gecos = cr.Spec.ForProvider.Gecos
	body.Lang = cr.Spec.ForProvider.Lang
	body.Timezone = cr.Spec.ForProvider.Timezone
	body.FreeformContactInfo = cr.Spec.ForProvider.FreeformContactInfo
	body.Comments = cr.Spec.ForProvider.Comments
	body.WorkPhone = cr.Spec.ForProvider.WorkPhone
	body.MobilePhone = cr.Spec.ForProvider.MobilePhone
	body.HomePhone = cr.Spec.ForProvider.HomePhone
	body.PagerPhone = cr.Spec.ForProvider.PagerPhone
	body.Organization = cr.Spec.ForProvider.Organization
	body.Address1 = cr.Spec.ForProvider.Address1
	body.Address2 = cr.Spec.ForProvider.Address2
	body.City = cr.Spec.ForProvider.City
	body.Zip = cr.Spec.ForProvider.Zip
	body.State = cr.Spec.ForProvider.State
	body.Country = cr.Spec.ForProvider.Country
	body.Password = cr.Spec.ForProvider.Password
	body.Name = cr.Spec.ForProvider.Name
	body.Disabled = rt.PerlBoolean(cr.Spec.ForProvider.Disabled)
	body.Privileged = rt.PerlBooleanInteger(cr.Spec.ForProvider.Privileged)

	return body, nil
}

// observation projects the read response onto status.atProvider.
func observation(in *rt.UserIdNameGet200Response) (v1alpha1.UserObservation, error) {
	out := v1alpha1.UserObservation{}

	if raw, err := json.Marshal(in.CustomFields); err == nil {
		out.CustomFields = string(raw)
	} else {
		return out, errors.Wrap(err, "CustomFields")
	}
	out.Id = string(in.Id)
	out.Created = in.Created
	if raw, err := json.Marshal(in.Creator); err == nil {
		out.Creator = string(raw)
	} else {
		return out, errors.Wrap(err, "Creator")
	}
	out.LastUpdated = in.LastUpdated
	if raw, err := json.Marshal(in.LastUpdatedBy); err == nil {
		out.LastUpdatedBy = string(raw)
	} else {
		return out, errors.Wrap(err, "LastUpdatedBy")
	}
	out.RealName = in.RealName
	out.NickName = in.NickName
	out.EmailAddress = in.EmailAddress
	out.Gecos = in.Gecos
	out.Lang = in.Lang
	out.Timezone = in.Timezone
	out.FreeformContactInfo = in.FreeformContactInfo
	out.Comments = in.Comments
	out.WorkPhone = in.WorkPhone
	out.MobilePhone = in.MobilePhone
	out.HomePhone = in.HomePhone
	out.PagerPhone = in.PagerPhone
	out.Organization = in.Organization
	out.Address1 = in.Address1
	out.Address2 = in.Address2
	out.City = in.City
	out.Zip = in.Zip
	out.State = in.State
	out.Country = in.Country
	out.Name = in.Name
	out.Disabled = string(in.Disabled)
	out.Privileged = int64(in.Privileged)
	if raw, err := json.Marshal(in.Memberships); err == nil {
		out.Memberships = string(raw)
	} else {
		return out, errors.Wrap(err, "Memberships")
	}
	if raw, err := json.Marshal(in.Hyperlinks); err == nil {
		out.Hyperlinks = string(raw)
	} else {
		return out, errors.Wrap(err, "_hyperlinks")
	}

	return out, nil
}

// upToDate compares only the fields the server answers under the same name
// and the same shape. A field it does not echo back -- a password, a body the
// server reshapes on the way out -- cannot be diffed without reporting drift
// on every reconcile, so it is left alone.
func upToDate(cr *v1alpha1.User, observed *rt.UserIdNameGet200Response) bool {
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.RealName != "" && cr.Spec.ForProvider.RealName != observed.RealName {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.NickName != "" && cr.Spec.ForProvider.NickName != observed.NickName {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.EmailAddress != "" && cr.Spec.ForProvider.EmailAddress != observed.EmailAddress {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Gecos != "" && cr.Spec.ForProvider.Gecos != observed.Gecos {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Lang != "" && cr.Spec.ForProvider.Lang != observed.Lang {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Timezone != "" && cr.Spec.ForProvider.Timezone != observed.Timezone {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.FreeformContactInfo != "" && cr.Spec.ForProvider.FreeformContactInfo != observed.FreeformContactInfo {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Comments != "" && cr.Spec.ForProvider.Comments != observed.Comments {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.WorkPhone != "" && cr.Spec.ForProvider.WorkPhone != observed.WorkPhone {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.MobilePhone != "" && cr.Spec.ForProvider.MobilePhone != observed.MobilePhone {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.HomePhone != "" && cr.Spec.ForProvider.HomePhone != observed.HomePhone {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.PagerPhone != "" && cr.Spec.ForProvider.PagerPhone != observed.PagerPhone {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Organization != "" && cr.Spec.ForProvider.Organization != observed.Organization {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Address1 != "" && cr.Spec.ForProvider.Address1 != observed.Address1 {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Address2 != "" && cr.Spec.ForProvider.Address2 != observed.Address2 {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.City != "" && cr.Spec.ForProvider.City != observed.City {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Zip != "" && cr.Spec.ForProvider.Zip != observed.Zip {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.State != "" && cr.Spec.ForProvider.State != observed.State {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Country != "" && cr.Spec.ForProvider.Country != observed.Country {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Name != "" && cr.Spec.ForProvider.Name != observed.Name {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Disabled != "" && cr.Spec.ForProvider.Disabled != string(observed.Disabled) {
		return false
	}
	// Only what the person actually set: an optional field left empty is not
	// a difference from whatever the server chose to put there.
	if cr.Spec.ForProvider.Privileged != 0 && cr.Spec.ForProvider.Privileged != int64(observed.Privileged) {
		return false
	}

	return true
}

// jsonEqual compares two JSON documents by value rather than by text, so that
// a server re-ordering an object's keys is not a permanent diff.
func jsonEqual(a, b string) bool {
	var left, right any

	if err := json.Unmarshal([]byte(a), &left); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(b), &right); err != nil {
		return false
	}

	x, err := json.Marshal(left)
	if err != nil {
		return false
	}
	y, err := json.Marshal(right)
	if err != nil {
		return false
	}

	return string(x) == string(y)
}

func (c *external) Observe(ctx context.Context, cr *v1alpha1.User) (managed.ExternalObservation, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		// Nothing has been created yet.
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	body, err := c.service.DoRequest(ctx, "GET", fmt.Sprintf("/user/%v", id), nil)
	if err != nil {
		// ONLY a 404 means it is gone. Any other failure (500, timeout,
		// throttling) must be surfaced -- treating it as "does not exist"
		// would provision a second one and orphan the first.
		if rt.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, errors.Wrap(err, errGet)
	}

	var observed rt.UserIdNameGet200Response
	if err := json.Unmarshal(body, &observed); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errParse)
	}

	at, err := observation(&observed)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errParse)
	}
	cr.Status.AtProvider = at

	// RT deletes this by disabling it, so after a successful delete the read
	// still answers -- and without this the finalizer never comes off. Only
	// while deleting: a disabled user nobody asked to delete still
	// exists, and saying otherwise would create a second one.
	if meta.WasDeleted(cr) && observed.Disabled == "1" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	if meta.WasDeleted(cr) {
		cr.Status.SetConditions(xpv2.Deleting())
	} else {
		cr.Status.SetConditions(xpv2.Available())
	}

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: upToDate(cr, &observed),
	}, nil
}

func (c *external) Create(ctx context.Context, cr *v1alpha1.User) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errParams)
	}

	respBody, location, err := c.service.DoCreateRequest(ctx, "POST", "/user", body)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
	}

	id := ""

	// A create that answers 201 with nothing but a Location header. The
	// identifier is in that header, and everything else the server assigned
	// has to be fetched.
	if len(respBody) == 0 {
		id = rt.IDFromLocation(location)
	} else {
		var created rt.UserIdNameGet200Response
		if err := json.Unmarshal(respBody, &created); err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		// Through %v because RT numbers its ids and an external name is a
		// string -- the annotation has to hold what the member path spells,
		// whichever of the two the document declared.
		id = fmt.Sprintf("%v", created.Id)

		at, err := observation(&created)
		if err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		cr.Status.AtProvider = at
	}

	if id == "" {
		return managed.ExternalCreation{}, errors.New(errNoID)
	}

	meta.SetExternalName(cr, id)

	return managed.ExternalCreation{}, nil
}

func (c *external) Update(ctx context.Context, cr *v1alpha1.User) (managed.ExternalUpdate, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		return managed.ExternalUpdate{}, errors.New(errUpdate)
	}

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errParams)
	}

	respBody, err := c.service.DoRequest(ctx, "PUT", fmt.Sprintf("/user/%v", id), body)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errUpdate)
	}

	// The update's answer is NOT the read's. RT replies to a PUT with a list
	// of what it changed -- ["Queue Description changed from 'a' to 'b'"] --
	// and parsing that as the object fails on every successful update. The
	// next Observe reports the new state, which is where status.atProvider
	// comes from anyway.
	_ = respBody

	return managed.ExternalUpdate{}, nil
}

func (c *external) Delete(ctx context.Context, cr *v1alpha1.User) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv2.Deleting())

	id := meta.GetExternalName(cr)
	if id == "" {
		// Never created; nothing to destroy.
		return managed.ExternalDelete{}, nil
	}

	// A 404 means someone else already did it, which is success as far as
	// reconciliation is concerned.
	_, err := c.service.DoRequest(ctx, "DELETE", fmt.Sprintf("/user/%v", id), nil)
	if err != nil && !rt.IsNotFound(err) {
		return managed.ExternalDelete{}, errors.Wrap(err, errDelete)
	}

	return managed.ExternalDelete{}, nil
}

func (c *external) Disconnect(_ context.Context) error {
	return nil
}
