// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Queue{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// QueueParameters are the configurable fields of a Queue.
//
// These are the fields of the create request body (QueuePostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// QueueObservation instead.
type QueueParameters struct {
	// Name Using an existing queue name will result in 400.
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Description
	// +optional
	Description string `json:"Description,omitempty"`

	// Lifecycle
	// +optional
	Lifecycle string `json:"Lifecycle,omitempty"`

	// SubjectTag
	// +optional
	SubjectTag string `json:"SubjectTag,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	// +optional
	SortOrder string `json:"SortOrder,omitempty"`

	// CorrespondAddress Reply Address in the UI
	// +optional
	CorrespondAddress string `json:"CorrespondAddress,omitempty"`

	// CommentAddress
	// +optional
	CommentAddress string `json:"CommentAddress,omitempty"`

	// SLADisabled
	// +optional
	SLADisabled string `json:"SLADisabled,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// QueueObservation are the observable fields of a Queue.
//
// These are the fields of the read response (QueueIdNameGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type QueueObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// CustomFields Customfields with their values, as returned by the server.
	CustomFields string `json:"CustomFields,omitempty"`

	// SLADisabled
	SLADisabled string `json:"SLADisabled,omitempty"`

	// Cc
	Cc string `json:"Cc,omitempty"`

	// AdminCc
	AdminCc string `json:"AdminCc,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	SortOrder string `json:"SortOrder,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// TicketCustomFields The custom fields applied to an object, as a queue lists the ones its tickets have. No values -- these are the fields themselves.
	TicketCustomFields string `json:"TicketCustomFields,omitempty"`

	// CommentAddress May be empty.
	CommentAddress string `json:"CommentAddress,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`

	// Lifecycle
	Lifecycle string `json:"Lifecycle,omitempty"`

	// Hyperlinks Things and operations related to this queue.
	Hyperlinks string `json:"_hyperlinks,omitempty"`

	// CorrespondAddress Reply Address in the UI
	CorrespondAddress string `json:"CorrespondAddress,omitempty"`

	// TicketTransactionCustomFields TODO
	TicketTransactionCustomFields string `json:"TicketTransactionCustomFields,omitempty"`

	// SubjectTag
	SubjectTag string `json:"SubjectTag,omitempty"`
}

// A QueueSpec defines the desired state of a Queue.
type QueueSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              QueueParameters `json:"forProvider"`
}

// A QueueStatus represents the observed state of a Queue.
type QueueStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 QueueObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Queue is a managed RT queue.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Queue struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   QueueSpec   `json:"spec"`
	Status QueueStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// QueueList contains a list of Queue
type QueueList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Queue `json:"items"`
}

// Queue type metadata.
var (
	QueueKind             = reflect.TypeOf(Queue{}).Name()
	QueueGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: QueueKind}.String()
	QueueKindAPIVersion   = QueueKind + "." + SchemeGroupVersion.String()
	QueueGroupVersionKind = SchemeGroupVersion.WithKind(QueueKind)
)

func init() {
	SchemeBuilder.Register(&Queue{}, &QueueList{})
}
