// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Article{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// ArticleParameters are the configurable fields of a Article.
//
// These are the fields of the create request body (ArticlePostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// ArticleObservation instead.
type ArticleParameters struct {
	// CustomFields Structure for uploading custom field values in POSTs and PUTs.
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	CustomFields string `json:"CustomFields,omitempty"`

	// Name
	// +optional
	Name string `json:"Name,omitempty"`

	// Summary
	// +optional
	Summary string `json:"Summary,omitempty"`

	// Class Name or numeric id of the class the article belongs to.
	// +kubebuilder:validation:Required
	Class string `json:"Class"`

	// SortOrder Seems to be an enumeration of some kind.
	// +optional
	SortOrder string `json:"SortOrder,omitempty"`

	// Parent Id of the parent article, if any.
	// +optional
	Parent int64 `json:"Parent,omitempty"`

	// URI
	// +optional
	URI string `json:"URI,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// ArticleObservation are the observable fields of a Article.
//
// These are the fields of the read response (ArticleIdGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type ArticleObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// CustomFields Customfields with their values, as returned by the server.
	CustomFields string `json:"CustomFields,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Summary
	Summary string `json:"Summary,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	SortOrder string `json:"SortOrder,omitempty"`

	// Class
	Class string `json:"Class,omitempty"`

	// Parent
	Parent string `json:"Parent,omitempty"`

	// URI
	URI string `json:"URI,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`
}

// A ArticleSpec defines the desired state of a Article.
type ArticleSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              ArticleParameters `json:"forProvider"`
}

// A ArticleStatus represents the observed state of a Article.
type ArticleStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 ArticleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Article is a managed RT article.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Article struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ArticleSpec   `json:"spec"`
	Status ArticleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArticleList contains a list of Article
type ArticleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Article `json:"items"`
}

// Article type metadata.
var (
	ArticleKind             = reflect.TypeOf(Article{}).Name()
	ArticleGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ArticleKind}.String()
	ArticleKindAPIVersion   = ArticleKind + "." + SchemeGroupVersion.String()
	ArticleGroupVersionKind = SchemeGroupVersion.WithKind(ArticleKind)
)

func init() {
	SchemeBuilder.Register(&Article{}, &ArticleList{})
}
