// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Group{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// GroupParameters are the configurable fields of a Group.
//
// These are the fields of the create request body (GroupPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// GroupObservation instead.
type GroupParameters struct {
	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Description
	// +optional
	Description string `json:"Description,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// GroupObservation are the observable fields of a Group.
//
// These are the fields of the read response (GroupIdGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type GroupObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// CustomFields Customfields with their values, as returned by the server.
	CustomFields string `json:"CustomFields,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// Hyperlinks Things and operations related to this queue.
	Hyperlinks string `json:"_hyperlinks,omitempty"`

	// Domain Enum likely incomplete.
	Domain string `json:"Domain,omitempty"`

	// Instance No idea what this means.
	Instance string `json:"Instance,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`

	// Members Member users and groups
	Members string `json:"Members,omitempty"`
}

// A GroupSpec defines the desired state of a Group.
type GroupSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              GroupParameters `json:"forProvider"`
}

// A GroupStatus represents the observed state of a Group.
type GroupStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 GroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Group is a managed RT group.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Group struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GroupSpec   `json:"spec"`
	Status GroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupList contains a list of Group
type GroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Group `json:"items"`
}

// Group type metadata.
var (
	GroupKind             = reflect.TypeOf(Group{}).Name()
	GroupGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupKind}.String()
	GroupKindAPIVersion   = GroupKind + "." + SchemeGroupVersion.String()
	GroupGroupVersionKind = SchemeGroupVersion.WithKind(GroupKind)
)

func init() {
	SchemeBuilder.Register(&Group{}, &GroupList{})
}
