// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Customfield{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// CustomfieldParameters are the configurable fields of a Customfield.
//
// These are the fields of the create request body (CustomfieldPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// CustomfieldObservation instead.
type CustomfieldParameters struct {
	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Type Custom field type.
	// +kubebuilder:validation:Required
	Type string `json:"Type"`

	// RenderType How the custom field is displayed in the UI.
	// +optional
	RenderType string `json:"RenderType,omitempty"`

	// LookupType What type of object this custom field applies to?
	// +kubebuilder:validation:Required
	LookupType string `json:"LookupType"`

	// ValidationHint
	// +optional
	ValidationHint string `json:"ValidationHint,omitempty"`

	// MaxValues Whether the field is single valued. Note that not all custom field types support multiple values.
	// +kubebuilder:validation:Required
	MaxValues string `json:"MaxValues"`

	// Description
	// +optional
	Description string `json:"Description,omitempty"`

	// EntryHint
	// +optional
	EntryHint string `json:"EntryHint,omitempty"`

	// UniqueValues
	// +optional
	UniqueValues string `json:"UniqueValues,omitempty"`

	// Pattern
	// +optional
	Pattern string `json:"Pattern,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	// +optional
	SortOrder string `json:"SortOrder,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// CustomfieldObservation are the observable fields of a Customfield.
//
// These are the fields of the read response (CustomfieldIdGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type CustomfieldObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Type Custom field type.
	Type string `json:"Type,omitempty"`

	// RenderType How the custom field is displayed in the UI.
	RenderType string `json:"RenderType,omitempty"`

	// LookupType What type of object this custom field applies to?
	LookupType string `json:"LookupType,omitempty"`

	// ValidationHint
	ValidationHint string `json:"ValidationHint,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// EntryHint
	EntryHint string `json:"EntryHint,omitempty"`

	// UniqueValues
	UniqueValues string `json:"UniqueValues,omitempty"`

	// Pattern
	Pattern string `json:"Pattern,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	SortOrder string `json:"SortOrder,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`

	// Values
	Values string `json:"Values,omitempty"`

	// Hyperlinks Things and operations related to this ticket. Probably contains multiple lifecycle operations.
	Hyperlinks string `json:"_hyperlinks,omitempty"`

	// MaxValues Whether the field is single valued
	MaxValues string `json:"MaxValues,omitempty"`
}

// A CustomfieldSpec defines the desired state of a Customfield.
type CustomfieldSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              CustomfieldParameters `json:"forProvider"`
}

// A CustomfieldStatus represents the observed state of a Customfield.
type CustomfieldStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 CustomfieldObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Customfield is a managed RT customfield.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Customfield struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomfieldSpec   `json:"spec"`
	Status CustomfieldStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomfieldList contains a list of Customfield
type CustomfieldList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Customfield `json:"items"`
}

// Customfield type metadata.
var (
	CustomfieldKind             = reflect.TypeOf(Customfield{}).Name()
	CustomfieldGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomfieldKind}.String()
	CustomfieldKindAPIVersion   = CustomfieldKind + "." + SchemeGroupVersion.String()
	CustomfieldGroupVersionKind = SchemeGroupVersion.WithKind(CustomfieldKind)
)

func init() {
	SchemeBuilder.Register(&Customfield{}, &CustomfieldList{})
}
