// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Class{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// ClassParameters are the configurable fields of a Class.
//
// These are the fields of the create request body (ClassPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// ClassObservation instead.
type ClassParameters struct {
	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Description
	// +optional
	Description string `json:"Description,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	// +optional
	SortOrder string `json:"SortOrder,omitempty"`

	// Disabled
	// +optional
	Disabled string `json:"Disabled,omitempty"`
}

// ClassObservation are the observable fields of a Class.
//
// These are the fields of the read response (ClassIdNameGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type ClassObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// SortOrder Seems to be an enumeration of some kind.
	SortOrder string `json:"SortOrder,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`
}

// A ClassSpec defines the desired state of a Class.
type ClassSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              ClassParameters `json:"forProvider"`
}

// A ClassStatus represents the observed state of a Class.
type ClassStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 ClassObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Class is a managed RT class.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Class struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClassSpec   `json:"spec"`
	Status ClassStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClassList contains a list of Class
type ClassList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Class `json:"items"`
}

// Class type metadata.
var (
	ClassKind             = reflect.TypeOf(Class{}).Name()
	ClassGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClassKind}.String()
	ClassKindAPIVersion   = ClassKind + "." + SchemeGroupVersion.String()
	ClassGroupVersionKind = SchemeGroupVersion.WithKind(ClassKind)
)

func init() {
	SchemeBuilder.Register(&Class{}, &ClassList{})
}
